auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “TY's Blog”
title: TY's blog
description: Everything about TY.
url: https://yangtiancoder.github.io/
feed: /atom.xml
author_info: <a href="http://yangtiancoder.github.io/">yangtiancoder</a>

theme: jekyll-theme-time-machine
